### ISSUE TITLE
Model Request: Google Gemini

### ISSUE THREAD

**Issue by dchuk** [saoudrizwan/claude-dev#58] opened 2024-08-09 01:37 UTC
I know (and agree) that Sonnet 3.5 is the current best API/model for code generation, but I think it would be good to offer Google’s Gemini models simply for their giant context windows, which are also useful for code generation because you can chuck so much more code and documentation in one API call.

Any interest in adding this? I can take a look at adding it myself with a pull request too. 

(Side question: I assume @saoudrizwan you’re using Claude Dev to iterate on Claude Dev…if so, mind explaining your workflow a bit given it’s a VSCode extension? Any tricks?)

**Comment by saoudrizwan** [comment] 2024-08-10 05:00
Choosing models is on the roadmap! 

> I assume you’re using Claude Dev to iterate on Claude Dev

Yes I am :-) Claude was a huge help with the new v1.0.98 update where you can now attach images to messages. My workflow was asking Claude to do something like:
1. Read all relevant files into context first 
2. Update <file names, you don't even have to be specific with the paths> with <feature>
3. Add pseudocode with any areas that you aren't sure how to implement to give me a good idea of how to complete the feature

I've also used it to write automation scripts i.e. I asked it to look at certain files where the version number was hardcoded, and it created a script `npm run upver 2.0` to update the version number in all these places using regex. (Although this is more of a temporary hack until I've refactored things to not use as many hardcoded values.)

I've also seen people use other cool workflows like asking Claude Dev to make a script that converts key files in their codebase into a single markdown file, and then reading that file at the beginning of each new task.

**Comment by dchuk** [comment] 2024-08-10 05:35
Can you expand on that last part about single markdown files being read at the beginning of tasks? That’s exactly what I was referring to in the other issue around ensuring Claude dev uses up to date library docs

**Comment by saoudrizwan** [comment] 2024-08-12 10:15
> Can you expand on that last part about single markdown files being read at the beginning of tasks?

It's nothing complicated, just a script to copy the contents of all files in a repository into a single markdown file. You could even ask Claude Dev to write a script like this for you. Then at the beginning of each task ask it to read this file (although this wouldn't work well for large enough projects).

v1.1.13 now also has the ability to specify custom instructions in settings, which get appended to the system prompt sent with every request. So you could add instructions like e.g. "Start each task by reading repo-map.md"

Regarding Gemini: v1.1.13 now lets you choose other Claude models (+ GPT-4o, DeepSeek, and Mistral if you use OpenRouter). I experimented with Gemini Pro 1.5 and Flash 1.5, and found that OpenRouter does not map their responses to tool calls properly. For example they return content with too many escapes (`\\\\n`), and throw errors for being in the wrong order when they're not. They also cannot handle feedback given to a request with multiple tools. So for the time being Gemini models on OpenRouter don't work with Claude Dev, but I will update the extension as soon as they fix these issues.

**Comment by chrisq084** [comment] 2024-09-02 13:51
@saoudrizwan do you have a timeline when we will be see google gemini as an option, im intrested in the video vision option.

**Comment by saoudrizwan** [comment] 2024-09-02 15:42
Better google gemini support is on the roadmap, closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/30

**Closed by saoudrizwan** 2024-09-02 15:42 UTC
Labels: enhancement
