### ISSUE TITLE
 'llama3-groq-70b-8192-tool-use-preview' unable to call tools 

### ISSUE THREAD

**Issue by kiranmaya** [saoudrizwan/claude-dev#98] opened 2024-08-14 19:00 UTC
i have attempted to write groq as an API provider. 
 
![Screenshot_5](https://github.com/user-attachments/assets/a40703e3-25f3-4e03-b02f-3155f94b971d)

tasks are not successful, 
am I doing wrong with integration, or "llama tool use" model at present is unable to call functions? 

`
import { Groq } from 'groq-sdk';
import { Anthropic } from "@anthropic-ai/sdk"
import { ApiHandler, withoutImageData } from '.';
import { ApiHandlerOptions, groqDefaultModelId, GroqModelId, groqModels, ModelInfo } from '../shared/api';

export class GroqHandler implements ApiHandler {
    private options: ApiHandlerOptions;
    private client: Groq;

    constructor(options: ApiHandlerOptions) {
        this.options = options;
        this.client = new Groq({ apiKey: "" });
    }

    getModel(): { id: GroqModelId; info: ModelInfo } {
		const modelId = this.options.apiModelId
		if (modelId && modelId in groqModels) {
			const id = modelId as GroqModelId
			return { id, info: groqModels[id] }
		}
		return { id: groqDefaultModelId, info: groqModels[groqDefaultModelId] }
	}

    async createMessage(
        systemPrompt: string,
        messages: Anthropic.Messages.MessageParam[],
        tools: Anthropic.Messages.Tool[]
    ): Promise<Anthropic.Messages.Message> {
        const groqMessages = this.convertToGroqMessages(systemPrompt, messages);
        const groqTools = this.convertToGroqTools(tools);

        const response = await this.client.chat.completions.create({
            model: this.getModel().id,
            messages: groqMessages,
            tools: groqTools,
            tool_choice: "auto",
            max_tokens: 6000,
        });

        return this.convertToAnthropicMessage(response);
    }

    createUserReadableRequest(
        userContent: Array<
            | Anthropic.TextBlockParam
            | Anthropic.ImageBlockParam
            | Anthropic.ToolUseBlockParam
            | Anthropic.ToolResultBlockParam
        >
    ): any {
        return {
            model: this.getModel().id,
            max_tokens: this.getModel().info.maxTokens,
            messages: [
                { role: "system", content: "(see SYSTEM_PROMPT in src/ClaudeDev.ts)" },
                { role: "user", content: withoutImageData(userContent) },
            ],
            tools: "(see tools in src/ClaudeDev.ts)",
            tool_choice: "auto",
        };
    }

	private convertToGroqMessages(
		systemPrompt: string,
		messages: Anthropic.Messages.MessageParam[]
	): Groq.Chat.ChatCompletionMessage[] {
		const groqMessages: Groq.Chat.ChatCompletionMessage[] = [];
	
		// Add the system prompt, assuming 'system' maps to 'assistant' or another valid Groq role
		groqMessages.push({
			role: 'assistant', // Replace with the correct role if needed
			content: systemPrompt,
		});
	
		// Convert each Anthropic message to a Groq message
		messages.forEach((message) => {
			groqMessages.push({
				role:"assistant", // Ensuring correct role mapping
				content: this.extractContent(message.content), // Ensuring content is handled correctly
			});
		});
	
		return groqMessages;
	}
	
 
	
	private extractContent(content: any): string {
		// Ensure content is in the correct format and is a string
		if (typeof content === 'string') {
			return content;
		} else if (Array.isArray(content)) {
			// If content is an array, join its elements as strings
			return content.map(c => typeof c === 'string' ? c : JSON.stringify(c)).join(' ');
		} else if (content && typeof content === 'object') {
			// If content is an object, convert it to a string
			return JSON.stringify(content);
		} else {
			return ''; // Default to an empty string if content is not recognized
		}
	}
	
	
	
	private convertToGroqTools(
		tools: Anthropic.Messages.Tool[]
	): Groq.Chat.ChatCompletionTool[] {
		return tools.map((tool) => ({
			type: 'function',
			function: {
				name: tool.name,
				description: tool.description,
				parameters: tool.input_schema, // Assuming `input_schema` is the correct format
			},
		}));
	}
	

    private convertToAnthropicMessage(
        response: Groq.Chat.ChatCompletion
    ): Anthropic.Messages.Message {
        const groqMessage = response.choices[0].message;
        const anthropicMessage: Anthropic.Messages.Message = {
            id: response.id,
            type: "message",
            role: groqMessage.role as "assistant",
            content: [
                {
                    type: "text",
                    text: groqMessage.content || "",
                },
            ],
            model: response.model,
            stop_reason: this.mapFinishReason(response.choices[0].finish_reason),
            stop_sequence: null,
            usage: {
                input_tokens: response.usage?.prompt_tokens || 0,
                output_tokens: response.usage?.completion_tokens || 0,
            },
        };

        if (groqMessage.tool_calls) {
            anthropicMessage.content.push(
                ...groqMessage.tool_calls.map(toolCall => ({
                    type: "tool_use" as const,
                    id: toolCall.id,
                    name: toolCall.function.name,
                    input: JSON.parse(toolCall.function.arguments || "{}"),
                }))
            );
        }

        return anthropicMessage;
    }

    private mapFinishReason(reason: string | null): Anthropic.Messages.Message['stop_reason'] {
        switch (reason) {
            case "stop":
                return "end_turn";
            case "length":
                return "max_tokens";
            case "tool_calls":
                return "tool_use";
            case "function_call":
                    return "tool_use";
            default:
                return null;
        }
    }
}`

**Comment by saoudrizwan** [comment] 2024-08-15 01:02
Hi thank you for looking into adding groq support! It looks like you're not mapping the groq sdk to anthropic types correctly, you can see an example of this in `openrouter.ts`. I have plans on adding groq and vertex support in the future anyways, after I've added Anthropic's new prompt caching which IMO is gonna be a game changer for claude dev - expect costs to be 10x less, way cheaper than groq calls to llama.

**Comment by kiranmaya** [comment] 2024-08-15 19:49
read the blog post on caching, but its limit is only 5 minutes, maybe they calculated 5 min from the last call time,groq and local inference of llama are free, I have tested its function calling ability, and it is pretty strong.

**Comment by sosacrazy126** [comment] 2024-08-16 05:45
i tired this to and was unsuccessful i was able to modify and make it usable with any open-router model i can share and that can be used as a base to build from

**Comment by saoudrizwan** [comment] 2024-09-02 16:15
Ollama and OpenAI support is in the works, closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/30

**Closed by saoudrizwan** 2024-09-02 16:15 UTC
