### ISSUE TITLE
Feature Request: Custom OpenAPI/Claude Endpoint Support

### ISSUE THREAD

**Issue by btiger** [saoudrizwan/claude-dev#76] opened 2024-08-11 05:28 UTC
Can you add the ability for users to configure and use custom OpenAPI/Claude endpoints in the application, allowing for integration with third-party OpenAPI/Claude services? some of the 3rd party services have no rate limitation.

**Comment by scarr05** [comment] 2024-08-11 11:36
I second this feature, something like LiteLLM akin to OpenwebUI supports would give the user the flexibility to use any LLM endpoint (supported by LiteLLM) they choose.

Claude 3.1 Sonnet works fantastic through Amazon Bedrock proxied through LiteLLM which i use for multiple VSCode ext and through OpenwebUI.

**Comment by BartNetJS** [comment] 2024-08-12 14:03
In version  v1.1.13 i noted "Added option to choose other Claude models (+ GPT-4o, DeepSeek, and Mistral if you use OpenRouter)"
Do i understand it correct that I need an OpenRouter account (and credits) to use gpt-4o?

**Comment by mkearl** [comment] 2024-08-12 14:10
That is correct

**Comment by BartNetJS** [comment] 2024-08-12 14:18
will there be an option in the future to use openai api keys directly?

**Comment by lucacri** [comment] 2024-08-13 05:12
Ollama support (or even better, LiteLLM) would be fantastic

**Comment by leiguangyan** [comment] 2024-08-13 05:37
hi, can this be deployed and used in an intranet environment?

**Comment by leiguangyan** [comment] 2024-08-13 05:44
Can this support models run by ollama?

**Comment by Batyan45** [comment] 2024-08-14 04:46
+1 for this request, it will be useful

**Comment by xvweirong** [comment] 2024-08-17 14:58
+1 same requirement, please allow to config custom base url for Claude/OpenAPI endpoints.

**Comment by danividalg** [comment] 2024-08-21 15:31
It could be great if it could be possible to use ollama, deepseek and or openai compatible API :)
Perhaps it could be needed a little bit modifications on prompts to be able to guide the model to reply as expected.

**Comment by saoudrizwan** [comment] 2024-09-02 15:52
Ollama support is on the roadmap, it's a bit more complicated than other providers since there's no knowing what the model is/stats which is a big part of the UI. Closing as dupe of https://github.com/saoudrizwan/claude-dev/issues/30#issuecomment-2325005847

**Closed by saoudrizwan** 2024-09-02 15:52 UTC
Labels: enhancement

**Comment by saoudrizwan** [comment] 2024-09-04 01:52
v1.5.19 now supports OpenAI compatible endpoints! To use ollama use the following:
base url: http://localhost:11434/v1
api key: ollama
model id: llama3.1 (or whatever model that supports tool use) 

Please keep in mind that claude dev uses complex prompts so it may not function nearly as well as claude 3.5 sonnet. I added a new error message in case he makes 3 mistakes in a row (mistakes mean invalid tool calls or no tool call whatsoever), so this should help you guide less capable models in the right direction.
![image](https://github.com/user-attachments/assets/42f5de75-be5f-4a7b-9996-75b0cae30030)

**Comment by saoudrizwan** [comment] 2024-09-07 11:54
You can now set a custom base URL for the Anthropic API in v.1.5.33:
![image](https://github.com/user-attachments/assets/9ca08767-aa2a-44f3-8f9e-e5ca01626b0c)

**Comment by sirus20x6** [comment] 2025-01-16 06:15
we need the ability to add multiple custom endpoints. I want llama.cpp with different models served at different endpoints, groq, crebras, etc. I should be able to add as many as I want

**Comment by oracleofsin** [comment] 2025-05-30 14:11
> we need the ability to add multiple custom endpoints. I want llama.cpp with different models served at different endpoints, groq, crebras, etc. I should be able to add as many as I want

hey there is not sure if you noticed yet but I just found the place to do it im adding our work endpoint now just select openapi compatible
