### ISSUE TITLE
Add Tavily support for web browsing

### ISSUE THREAD

**Issue by arunkr93** [saoudrizwan/claude-dev#116] opened 2024-08-16 03:36 UTC
Claude dev is currently limited by the knowledge cutoff of the model. It would be great if we add web browsing capability to search for issues or docs, so it can be prompted to check for the latest information when integrating APIs or finding bugs.

Let's add TAVILY !

**Comment by CiberNin** [comment] 2024-08-16 14:09
Duplicate of #102

**Closed** 2024-08-27 07:31 UTC
