### ISSUE TITLE
Getting an error setting up Ollama3.1

### ISSUE THREAD

**Issue by betoaldaba** [saoudrizwan/claude-dev#219] opened 2024-09-04 09:47 UTC
I get an error 
`API Request Failed

400 json: cannot unmarshal array into Go struct field Message.messages.content of type string`

Is there something I did wrong during install?

**Comment by saoudrizwan** [comment] 2024-09-04 19:42
@twoody2007 you can use ollama in claude dev in the latest v1.5.26, open settings > providers > ollama

**Comment by callbacked** [comment] 2024-09-04 20:20
Doesn't seem to work, I keep getting a "Connection Error" message after sending something

**Comment by twoody2007** [comment] 2024-09-04 20:23
> @twoody2007 you can use ollama in claude dev in the latest v1.5.26, open settings > providers > ollama

OK I will give it a try.

also: thanks for putting this together!

**Comment by NemoSomnium** [comment] 2024-09-04 20:51
> Doesn't seem to work, I keep getting a "Connection Error" message after sending something. I made sure Ollama is running via localhost:1134.

Same for me, it's trying to make api calls on a certain high numbered port and ollama server is running at a different port. I don't see a setting in claude dev for setting up how it should query ollama. Only to specify the ollama model

**Comment by saoudrizwan** [comment] 2024-09-04 21:28
@callbacked @NemoSomnium if you're using a different port than the default http://localhost:11434 then you can use openai compatible as your api provider and provide 'ollama' for the api key. I'll work on adding a custom base url field for ollama

**Comment by twoody2007** [comment] 2024-09-04 21:34
@saoudrizwan just gave it a spin. You're first comment is accurate: the local models appear to have insufficient responses. Looks like the Anthropic API wins ...for now!

**Comment by Arnaud3013** [comment] 2024-09-04 23:44
If using lmstudio, use "noop" as API key. But any model i've tried, i got "Claude is having trouble..." someone have a model working even if not that smart?

**Comment by twoody2007** [comment] 2024-09-05 16:33
@Arnaud3013 I am not sure what you mean by using "noop" as an API key, but you definitely need to have an actual key to make anything work.

I haven't seen Claude have issues responding yet; but I have seen problems with smaller models.

**Comment by abhaymin** [comment] 2024-09-05 17:57
> @callbacked @NemoSomnium if you're using a different port than the default http://localhost:11434 then you can use openai compatible as your api provider and provide 'ollama' for the api key. I'll work on adding a custom base url field for ollama

Hi @saoudrizwan 

As I am also interested in this feature to use a different endpoint for a ollama box. I made fork of your code and add this in the Ollama Config Page. Can I do a contribution for this change, if your ok.

**Comment by twoody2007** [comment] 2024-09-05 17:59
@Arnaud3013 oh I see - I was just using Ollama locally on the same machine.

Is it not possible to set up an API key? Seems odd that an API would be "OpenAI compatible" but not support the use of API key in the same way the OpenAI api does ...

**Comment by Arnaud3013** [comment] 2024-09-05 18:02
@twoody2007 It does support api key. But if using lmstudio instead of ollama, if you don't define an api key inside lmstudio, you can use noop as key. Maybe another could work, i havn't tried it.
But main issue is that it never finish a task without error with any model i've tried.

**Comment by AllyourBaseBelongToUs** [comment] 2024-09-06 01:38
@Arnaud3013 

You can enter anything as the API key it doesnt matter, be it Ollama, LM studio, Llama.cpp, Local.Ai or whatever you use.

Just make sure something is inside so not to get an "no key" error

@saoudrizwan 

Ollama´s biggest issue I've seen so far is that it Truncates the input (2048 token max) even if the model is capable of handling up to 200k (Dolphin model for example)

Using Llama.cpp server that issue isn't there, yet small models are pretty much unusable and it seems to have an issue with file generation (might be because I use Cursor instead of VS Code)

**Comment by iamspido** [comment] 2024-09-06 02:32
I use vs code under mac and I got following:
API Request Failed
Connection error.

I tryed API Provider Ollama and OpenAI Compatible both don't work and give the same error.
In browser `http://localhost:11434/` gives back Ollama is running and `curl http://localhost:11434/api/generate -d '{ "model": "llama3.1:8b", "prompt": "Hey" }'` gives back a positiv response.

**Comment by yuanqiuye** [comment] 2024-09-06 10:30
> I use vs code under mac (M2 Pro and 14.6.1) and I got following: API Request Failed Connection error.

Same, using ollama 0.3.9, ClaudeDev 1.5.32

**Comment by AllyourBaseBelongToUs** [comment] 2024-09-06 20:53
> I use vs code under mac (M2 Pro and 14.6.1) and I got following: API Request Failed Connection error.
> 
> I tryed API Provider Ollama and OpenAI Compatible both don't work and give the same error. In browser `http://localhost:11434/` gives back `Ollama is running` and `curl http://localhost:11434/api/generate -d '{ "model": "llama3.1:8b", "prompt": "Hey" }'` gives back a positiv response.

WHat error exactly?

try starting ollama with

ollama serve

there you might get mroe information on what is going wrong

**Comment by iamspido** [comment] 2024-09-07 00:17
> > I use vs code under mac (M2 Pro and 14.6.1) and I got following: API Request Failed Connection error.
> > I tryed API Provider Ollama and OpenAI Compatible both don't work and give the same error. In browser `http://localhost:11434/` gives back `Ollama is running` and `curl http://localhost:11434/api/generate -d '{ "model": "llama3.1:8b", "prompt": "Hey" }'` gives back a positiv response.
> 
> WHat error exactly?
> 
> try starting ollama with
> 
> ollama serve
> 
> there you might get mroe information on what is going wrong

When I start ollama with `ollama serve`, no entries are added to the log when executing claude dev. The error message `API Request Failed Connection error.` is the only one I get in VS Code. If you tell me how I can provide a more detailed log, I would be happy to supply it to you.

**Comment by saoudrizwan** [comment] 2024-09-23 22:27
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/330

**Closed by saoudrizwan** 2024-09-23 22:27 UTC
