### ISSUE TITLE
Losing large blocks of code during code review

### ISSUE THREAD

**Issue by joegiglio** [saoudrizwan/claude-dev#170] opened 2024-08-26 01:06 UTC
I have been using Claude-Dev to try to build a helpdesk ticketing application.  I have been documenting my journey and open sourced the code here:
https://github.com/joegiglio/helpdesk-claude-dev-ai

I have had some challenges, mostly around API limits but that has nothing to do with Claude-Dev. 

However, over the last couple of days, I have noticed that after prompting through Claude-Dev, I am shown proposed new code as usual BUT it also removes huge blocks of existing code, replacing it with a comment.   When I first saw this last night, I thought it was a one time quirk but I have seen it a few times since then and it is crippling me.

Is this a new bug?  Is my app.py file too large?  It is currently 510 lines.  Some type of token issue?

Here are a couple of examples: 

![lost code 1](https://github.com/user-attachments/assets/eb9f2cdc-ebd3-41c7-8353-c13aa0fe8b51)
![lost code 2](https://github.com/user-attachments/assets/d17deecd-d46a-4e74-ae01-c6228b7ea8c1)

I had another example but lost the screenshot.  :(

**Comment by joegiglio** [comment] 2024-08-26 01:19
Actually, it sounds like this is a dupe of https://github.com/saoudrizwan/claude-dev/issues/14 and a possible limitation of Claude?

That really sucks.  I was enjoying this project!

Does Cursor have a similar issue?  A lot of people seem to have made the switch but if the underlying issue is due to Claude, I can't see it being much different.

**Comment by saoudrizwan** [comment] 2024-08-26 04:46
Hey there! I have tried structured outputs like diffs but it significantly reduces quality of responses (can't even make a snake game on the first try). A common workaround for this issue is instead of accepting the changes, respond in the textfield "do not omit any code" and claude will redo it the correct way. Anthropic is releasing a new feature called Fast Edit Mode soon that should fix this issue, so pls stay tuned! (Closing as dupe of #14)

**Closed by saoudrizwan** 2024-08-26 04:46 UTC

**Comment by saoudrizwan** [comment] 2024-09-02 15:08
v1.5.6 now let's you edit Claude's changes before accepting! When he edits or creates a file, you can modify his changes directly in the right side of the diff view. You can even hover over a 'Revert Block' arrow button in the center to undo `// rest of code here` shenanigans when he deletes a bunch of code.
