### ISSUE TITLE
deepseek 2.5 error

### ISSUE THREAD

**Issue by rakibulmuhajir** [saoudrizwan/claude-dev#247] opened 2024-09-06 12:11 UTC
deepseek dropped new model yesterday and i decided to give it a try. i selected openai compatible under API Provider and model provider is following
https://api.deepseek.com
model is
deepseek-chat

this is the error

API Request Failed

422 Failed to deserialize the JSON body into the target type: messages[1]: invalid type: sequence, expected a string at line 17 column 3

{
  "model": "deepseek-chat",
  "system": "(see SYSTEM_PROMPT in src/ClaudeDev.ts)",
  "messages": [
    {
      "conversation_history": "..."
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "<task>\nwhat is your knowledge cut off time?\n</task>\n\n<potentially_relevant_details>(see getPotentiallyRelevantDetails in src/ClaudeDev.ts)</potentially_relevant_details>"
        }
      ]
    }
  ],
  "tools": "(see tools in src/ClaudeDev.ts)",
  "tool_choice": "auto"
}

**Comment by ValDyZ69** [comment] 2024-09-06 20:03
Hi , same error on my side

**Comment by xvweirong** [comment] 2024-09-07 02:24
Tried https://api.deepseek.com/v1 same error

API Request Failed

422 Failed to deserialize the JSON body into the target type: messages[1]: invalid type: sequence, expected a string at line 17 column 3
{
  "model": "deepseek-chat",
  "system": "(see SYSTEM_PROMPT in src/ClaudeDev.ts)",
  "messages": [
    {
      "conversation_history": "..."
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "<task>\nHi\n</task>\n\n<potentially_relevant_details>(see getPotentiallyRelevantDetails in src/ClaudeDev.ts)</potentially_relevant_details>"
        }
      ]
    }
  ],
  "tools": "(see tools in src/ClaudeDev.ts)",
  "tool_choice": "auto"
}

**Comment by bozertron** [comment] 2024-09-07 09:14
Same. Custom integration plausible?

**Comment by khchan8** [comment] 2024-09-09 13:25
same here.. how can we resolve this issue?

**Comment by a414166402** [comment] 2024-09-09 14:38
"model": "deepseek-coder",
      "apiBase": "https://api.deepseek.com/beta"
      Try this?

**Comment by zob** [comment] 2024-09-09 21:34
Duplicate of #230

**Comment by saoudrizwan** [comment] 2024-09-11 03:25
It looks like this is due to a limitation in deepseek's api not being able to accept arrays of user content. Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/230

**Closed by saoudrizwan** 2024-09-11 03:25 UTC
