### ISSUE TITLE
Stop claude from using placeholders

### ISSUE THREAD

**Issue by alreadyarrived** [saoudrizwan/claude-dev#77] opened 2024-08-11 07:47 UTC
Sometimes (though not as often as GPT), it creates stuff like:

`//this code remains unchanged`

And of course this destroys whatever code was there.

I know 'aider' has a check for a 'find and replace', where the find requires an exact match before replacing - but was wondering if claude dev could have a similar check to ensure that there is no code that suddenly goes missing

**Comment by SamPink** [comment] 2024-08-11 07:59
This happens to me sometimes too

**Comment by chris-battle-bunnings** [comment] 2024-08-11 11:39
Yep, same.

**Comment by saoudrizwan** [comment] 2024-08-12 08:20
Applying edits is a [hard problem](https://github.com/saoudrizwan/claude-dev/issues/14#issuecomment-2244433366). I tried something similar to aider where instead of Claude providing the full file contents, it would only provide the modified sections. Despite the algorithm working, I noticed a reduction in quality. It turns out when you force LLMs to adhere to a structured output format, its step-by-step/reasoning capabilities become significantly diminished. I've also read that OpenAI's new structured output API performs worse when doing step-by-step prompts, so this problem isn't specific to Claude. 

I recommend using the Anthropic provider option if you don't already, since it has a max output of 8192 tokens whereas OpenRouter doesn't handle large outputs well and AWS Bedrock is capped at 4096 tokens. You can also try breaking your file down into smaller files.

**Comment by saoudrizwan** [comment] 2024-08-12 09:22
Duplicate of #14, please see [this comment](https://github.com/saoudrizwan/claude-dev/issues/14#issuecomment-2283482762).

**Closed by saoudrizwan** 2024-08-12 09:22 UTC
