### ISSUE TITLE
Local Inference Option???  We need to save money please !

### ISSUE THREAD

**Issue by m-marinucci** [saoudrizwan/claude-dev#183] opened 2024-08-27 11:40 UTC
One should be able to select local inference LLM through LM studio for instance or directly with Ollama

Thanks!

**Comment by ajnart** [comment] 2024-08-27 14:00
@m-marinucci  I believe the following PR will address just that: https://github.com/saoudrizwan/claude-dev/pull/162

**Comment by saoudrizwan** [comment] 2024-09-02 17:17
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/95

**Closed by saoudrizwan** 2024-09-02 17:17 UTC
