### ISSUE TITLE
Feature Request - Can we please add options for manual Rate Limits please?

### ISSUE THREAD

**Issue by amritbanerjee** [saoudrizwan/claude-dev#75] opened 2024-08-10 23:45 UTC
As Topic suggests. Can we please add options for the following Rate Limits please? Max task per job is too simple especially given anthropics recent errors. I rather have the flexibility to run it slowly stably.

Rate Limits
Requests per minute (RPM)
Tokens per minute (TPM)
Tokens per day (TPD)

Great job on creating this. Has consistently taken over aider now I feel.

**Comment by saoudrizwan** [comment] 2024-08-12 09:47
Thank you for the feedback! These would be good options to have especially once I've implemented auto-approval for tool use.

**Comment by saoudrizwan** [comment] 2024-09-02 15:47
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/54

**Closed by saoudrizwan** 2024-09-02 15:47 UTC
Labels: enhancement
