### ISSUE TITLE
became incredibly slow

### ISSUE THREAD

**Issue by androb** [saoudrizwan/claude-dev#31] opened 2024-07-29 19:39 UTC
I used this yesterday, and it was phenomenal - fast and effective.

Now, it is incredibly and unusably slow. It takes multiple minutes to do each step.

I have tried rebooting but see the same issue.

Sorry, I don't have any more precise info, but I thought you should know in case there was something changed in the latest build.

**Comment by saoudrizwan** [comment] 2024-07-29 23:38
When you say incredibly slow, do you mean the API requests take a long time?

**Comment by saoudrizwan** [comment] 2024-07-30 02:20
It looks like this is an issue caused by the new `analyze_project` tool, which for large projects could be problematic getting all source definitions and file paths into context. I'll have to work on optimizing this somehow or at the very least not output the analysis to the chat view gui.

**Comment by GumDeveloper** [comment] 2024-07-30 07:28
analyzing a project folder would be a nice addition to minimize overhead.
also a direct selection of project-files would spice this even up.

just my 2 cents and: great work so far - really interesting !

**Comment by saoudrizwan** [comment] 2024-07-30 08:37
@GumDeveloper thank you! Quick question–are you experiencing issues with the extension taking a long time to load up or send a message, even before conversations get long?

**Comment by saoudrizwan** [comment] 2024-07-30 15:10
![image](https://github.com/user-attachments/assets/a5430826-72a2-4678-90ef-dfc3dd45a432)

Did you see the bottom part before it stuck and you had to restart?

**Comment by saoudrizwan** [comment] 2024-07-30 17:00
I think the likely culprit here is web-tree-sitter. It's essentially a wasm that gets executed whenever the analyze_project tool is called, and I think it's getting into a weird state for some users' architectures + analyze really big projects. @androb was able to get things working smoothly by downgrading to v0.0.6 which does not import web-tree-sitter. 

Just the fact that downgrading fixes this crosses out a lot of the theories I had as to what could be causing this–it can't be state related since state doesn't clear between downgrading/upgrading versions. It doesn't have anything to do with the new react virtualized list changes since @androb installed a version with that removed and still faced issues. 

I just released v1.0.64 which removes web-tree-sitter entirely, the analyze_project tool now just returns a list of all your files' names, so please update to this version and let me know if you are still running into this problem.

**Comment by CiberNin** [comment] 2024-07-30 18:22
Maybe analyze tool is coming at it from the wrong angle. Maintain a "context tree" that is built on boot and auto updated. 
Instead of analyze tool Claude could have a "focus" tool that lets it focus on a certain file / folder. And that would be the starting point in the context tree which we walk from to fill the context token buffer.
Maybe less of a context tree than a context graph. Obviously if project is small enough then it would be nice to shove all file contents into context. Once context overflows then prioritize files by "proximity" in file tree. Least important file removed first. Maybe store summarized versions to devolve to? ultimately devolving to just filename and maybe stats like file size.
For known languages maybe raise context priority of imported / importing files for current focus.

**Comment by GumDeveloper** [comment] 2024-07-31 04:55
> Did you see the bottom part before it stuck and you had to restart?

no, i didnt.

**Comment by GumDeveloper** [comment] 2024-07-31 08:23
![grafik](https://github.com/user-attachments/assets/0b18b468-2186-48c8-a96a-abebecc5c0e5)

**Comment by saoudrizwan** [comment] 2024-07-31 16:29
@GumDeveloper can you please provide more details, like what exactly resulted in that popup? Did it show up immediately or after a certain tool was called?

Looking into web-tree-sitter and WASMs in general, there's a lot of potential for memory issues to come up when processing a lot of files at once. And this popup leads me to believe that this is exactly what happened in your case when running the analyze_project tool for your very large project. 

I suggest giving some of the suggestions in this thread a try https://stackoverflow.com/questions/57887568/vs-code-crashing-on-restart-after-opening-large-file

Basically you'll need to delete the backup cache folder vscode keeps (I believe this is the root cause of the extension being "laggy" even when restarting vscode–there may be some persitent process or cache that keeps trying to get loaded into memory from the failed analyze_project attempt).

**Comment by saoudrizwan** [comment] 2024-07-31 16:36
@CiberNin thank you for your suggestion. I've just implemented something that I think is similar to your idea, where claude first lists all file paths, then can choose which directory to get source code definitions for (only for files at the top level, not recursively). This way it only gets definitions most relevant to the task at hand, without overwhelming its context window or user's memory constraints.

Check it out in v1.0.7 and [read more about it here](https://github.com/saoudrizwan/claude-dev?tab=readme-ov-file#working-in-existing-projects). 

I'm going to close this issue for now, but feel free to re-open if you run into the same problem again. Besides just processing top level files only for specific directories, I've also added a limit of 50 max files to parse for each request–so it's unlikely that web-tree-sitter ever gets the opportunity to run into these memory issues again. 

Thank you all for your feedback!

**Closed by saoudrizwan** 2024-07-31 16:36 UTC
Labels: bug

**Comment by saoudrizwan** [comment] 2024-08-02 23:06
Related: https://github.com/sourcegraph/cody/issues/3799

**Comment by TakaoWing** [comment] 2025-12-14 15:12
## Deep Code Reading結果 Part 2: コンテキスト収集メカニズム

### 2.1 メンションベースのコンテキスト収集

**場所**: `/src/core/mentions/index.ts`

Clineは6種類のメンションをサポートしてコンテキストを収集します：

#### 1. ファイルメンション (`@/path/to/file`)
- ファイルパスを解析して内容を抽出
- マルチワークスペース検索をサポート（すべてのルートで並列検索）
- ワークスペース接頭辞付きメンション: `workspace-name:/path/to/file`
- バイナリファイルを検出してスキップ
- フォルダ構造とファイル内容を含む

#### 2. フォルダメンション (`@/path/to/folder/`)
- ツリー形式でフォルダ構造をリスト
- `<file_content>`タグで第一レベルのファイル内容を含む
- バイナリファイルを適切に処理

#### 3. URLメンション (`@http://...`)
- `UrlContentFetcher`を介してブラウザを起動
- HTMLをMarkdownに変換
- ユーザー通知付きのエラー処理を提供

#### 4. 問題メンション (`@problems`)
- hostbridge経由で`getDiagnostics()`を呼び出し
- エラーと警告の重要度を持つVSCode診断情報を収集

#### 5. ターミナルメンション (`@terminal`)
- `getLatestTerminalOutput()`で最新のターミナル出力を取得

#### 6. Gitメンション
- `@git-changes`: `getWorkingState()`で作業ディレクトリの状態
- `@commit-hash`: `getCommitInfo()`でコミット情報

### 解析パイプライン (`parseMentions`関数)
- `mentionRegexGlobal`を使用した正規表現ベースのメンション抽出
- メンションをコンテンツブロックに変換: `<file_content>`, `<folder_content>`, `<url_content>`, `<workspace_diagnostics>`, `<terminal_output>`, `<git_working_state>`, `<git_commit>`
- テレメトリでメンションを追跡（`captureMentionUsed`, `captureMentionFailed`）
- フォールバック戦略を使用したマルチワークスペース並列検索を処理

**Comment by TakaoWing** [comment] 2025-12-14 15:15
## Deep Code Reading結果 Part 6: パス解決戦略

### 4.2 パス解決戦略

**場所**: `/src/core/workspace/`

マルチステップパス解決：

#### 1. ワークスペースヒントの解析
- ワークスペース接頭辞付きパスを検出: `workspace-name:/path`
- ワークスペースヒントと相対パスを抽出

#### 2. マルチルートパス適応 (`WorkspacePathAdapter`)
- 相対パスをすべての利用可能なワークスペースルートにマップ
- 明示的なワークスペースヒントを優先
- すべてのワークスペースを検索するフォールバック

#### 3. シングルルートフォールバック
- 非マルチルートの標準 `path.resolve(cwd, relativePath)`

### 重要な実装ポイント

1. **マルチワークスペースサポート**: Clineは複数のワークスペースルートを完全にサポートし、ワークスペースヒントを使用して特定のワークスペースをターゲットにできる

2. **フォールバック戦略**: ワークスペースヒントが提供されない場合、Clineはすべてのワークスペースを並列で検索し、最適な結果を見つけようとする

3. **パフォーマンス最適化**: 検索は並列で実行され、結果は効率的に集約される

**Comment by TakaoWing** [comment] 2025-12-14 15:15
## Deep Code Reading結果 Part 7: WebViewベースのコンテキスト選択

### 5.1 コンテキストメニュー実装

**場所**: `/webview-ui/src/utils/context-mentions.ts`

ユーザーが`@`を入力したときに、WebViewが自動補完コンテキストメニューを提供：

#### メニューオプション（プラットフォームに基づく動的順序）
1. URL
2. ターミナル（サポートされている場合）
3. 問題（Problems）
4. Git変更/コミット
5. フォルダ（ファイル検索から）
6. ファイル（ファイル検索から）

#### 動的検索統合
- ユーザーが`@`の後に入力するとFzfによるファジー検索をトリガー
- クエリでバックエンドに`searchFiles` RPCを呼び出し
- バックエンドがマッチングファイル/フォルダで応答
- リアルタイムでコンテキストメニューを結果で更新

### 5.2 メンション挿入ロジック

```typescript
insertMention(text, position, value, partialQueryLength)
- 最後の@記号を見つける
- 部分クエリを完全なメンションに置換
- スペースを含むパスを自動引用符で囲む
- 新しいテキストとカーソル位置を返す
```

### 5.3 コンテキストメニュークエリアイテム

```typescript
interface ContextMenuQueryItem {
  type: "file" | "folder" | "problems" | "terminal" | "url" | "git"
  value: string (実際のメンション)
  label: string (表示名)
  description: string (パスまたはメタデータ)
  workspaceName?: string (マルチワークスペース用)
}
```

**Comment by TakaoWing** [comment] 2025-12-14 15:16
## Deep Code Reading結果 Part 8: コンテキストウィンドウ管理

### 6.1 コンテキスト圧縮戦略

**場所**: `/src/core/context/context-management/ContextManager.ts`

- コンテキストウィンドウ制限に対してトークン使用量を監視
- ファイル読み取りの最適化（重複排除）を実行:
  - 会話全体で重複するファイル読み取りを識別
  - 重複を`duplicateFileReadNotice()`で置換
  - 30%以上のトークンを節約すると切り詰めをトリガー

#### 切り詰めオプション
- `"quarter"`: メッセージの1/4を保持
- `"half"`: メッセージの1/2を保持
- `"lastTwo"`: 最後のユーザー・アシスタントペアを保持
- `"none"`: 最初のペアのみ保持

### 6.2 コンテキスト変更追跡
- コンテキスト変更をディスクに永続化
- チェックポイント/レジューム機能をサポート
- バイナリ検索最適化のためにタイムスタンプで変更を追跡

## 主要な設計パターン

### 8.1 マルチワークスペースサポート
- ツールパラメータのワークスペースヒント: `workspace-name:/path`
- ワークスペース間の並列検索
- レガシー互換性のためのプライマリワークスペースへのフォールバック

### 8.2 セキュリティとアクセス制御
- コンテキストアクセスを制限する`.clineignore`ファイル
- ルート/ホームディレクトリスキャンを防ぐパス検証
- コンテキストの破損を避けるためのバイナリファイル検出
- 機密操作の承認フロー

### 8.3 パフォーマンス最適化
- 幅優先ファイル探索制限（200-5000ファイル）
- より高速な検索のためのgitignoreの尊重
- ウォッチャーノイズを減らすChokidarアトミック書き込み検出
- 並列マルチワークスペース検索

### 8.4 エラー処理
- 欠落ファイルの適切な劣化
- 失敗したメンションのテレメトリ追跡
- コンテキスト取得エラーのユーザー通知
- 権限エラー検出（`EACCES`、`ENOENT`）

**Comment by TakaoWing** [comment] 2025-12-14 15:17
## まとめ

ClineのVSCode上でのコンテキスト収集は、以下の特徴を持つ高度に洗練されたシステムです：

### 主要な発見

1. **ファイル検出**: マルチバックエンドアプローチ（globby + ripgrep）とスマートな制限
2. **コンテキストタイプ**: 6つのメンションタイプ（ファイル、フォルダ、URL、診断情報、ターミナル、git）
3. **VSCode統合**: IDE API呼び出しのためのgRPCベースのhostbridge
4. **マルチワークスペース**: ワークスペースヒントとフォールバック戦略の完全サポート
5. **ファイル追跡**: 古いコンテキストを防ぐChokidarベースの監視
6. **コンテキスト管理**: インテリジェントなトークンベースの圧縮と重複排除
7. **WebView UI**: ファジー検索付きの動的自動補完コンテキストメニュー
8. **セキュリティ**: .clineignore制御とパス検証

### 受け入れ条件の達成状況

✅ **Clineの実装を読み、コンテキスト収集の仕組みを理解している**
- ファイル探索からコンテキスト管理まで、完全な処理フローを理解

✅ **関連ファイルやメソッドの特定ができている**
- 主要なファイルとメソッドをすべて特定し、その役割を文書化

✅ **コンテキスト収集の方法がドキュメント化されている**
- 8つのパートに分けて詳細に文書化完了

### 調査観点の回答

**Q: Clineがどのようにファイルを探索しているか？**
A: globbyとripgrepの2つのバックエンドを使用し、幅優先探索で効率的にファイルを探索。デフォルトの無視パターンと.gitignoreを尊重。

**Q: 関連ファイル・メソッドの特定ロジックは？**
A: @メンションシステムとツール（ListFiles、SearchFiles、ReadFile）を通じて、ユーザーが指定したファイルやパターンに基づいて特定。

**Q: VSCode APIの活用方法は？**
A: gRPCライクなhostbridgeプロトコルを使用し、ワークスペース操作、ウィンドウ操作、診断情報取得などでVSCode APIを活用。

アーキテクチャは包括的なエラー処理、テレメトリ、マルチワークスペースサポートを備えた実用的なものです。
