### ISSUE TITLE
Issue while building a simple flask user login application

### ISSUE THREAD

**Issue by marketcalls** [saoudrizwan/claude-dev#5] opened 2024-07-16 01:27 UTC
App is Good. But the majority of the time getting this error
for building a simple flask user login app.

API request failed: 400 {"type":"error","error":{"type":"invalid_request_error","message":"Output blocked by content filtering policy"}}

**Comment by saoudrizwan** [comment] 2024-07-16 06:56
According to [Anthropic support](https://support.anthropic.com/en/articles/9205721-why-am-i-receiving-an-output-blocked-by-content-filtering-policy-error), this measure is "in efforts to prevent Claude from being used to replicate or regurgitate pre-existing materials." I haven't encountered this issue before, so I don't believe the system prompt or tool prompts are the cause. Could you please provide more context, such as your specific prompt?

**Comment by marketcalls** [comment] 2024-07-16 07:07
Prompt used "Build a Simple Flask user management with tailwind and daisy UI"

**Comment by saoudrizwan** [comment] 2024-07-19 04:28
Thank you, I will have to investigate if there's some way I can modify the system prompt to better handle such generic tasks.

**Comment by saoudrizwan** [comment] 2024-08-03 23:48
I have updated the system prompt quite a bit since this issue was opened, so please try using the latest version (1.0.9) and see if you still run into this issue. Closing for now.

**Closed by saoudrizwan** 2024-08-03 23:48 UTC
Labels: bug
