### ISSUE TITLE
Why does this 422 error occur when I use Deepseek's API to call services

### ISSUE THREAD

**Issue by yxl23** [saoudrizwan/claude-dev#258] opened 2024-09-09 08:19 UTC
![image](https://github.com/user-attachments/assets/1e6abce8-2fea-47c4-8b0d-a8261f9cf240)
![image](https://github.com/user-attachments/assets/ecf0f001-5efc-4453-a95a-f2c1841826df)

**Comment by kkrusher** [comment] 2024-09-09 13:00
I came across the same issue.

**Comment by khchan8** [comment] 2024-09-09 13:28
You need to change the base URL to be https://api.deepseek.com/v1
but even that is not working..

**Comment by zob** [comment] 2024-09-09 21:33
I'd say this is a duplicate of #230

**Comment by chatterzhao** [comment] 2024-09-12 17:01
I came across the same issue.

**Comment by chatterzhao** [comment] 2024-09-12 17:27
use: https://openrouter.ai/docs/models

<img width="481" alt="image" src="https://github.com/user-attachments/assets/f62ef268-e162-434b-ac0c-bd5600e59c2a">

<img width="778" alt="image" src="https://github.com/user-attachments/assets/5dea5cc5-e6ed-4189-bd68-8f68ad6c3b14">

**Comment by chatterzhao** [comment] 2024-09-12 17:32
> use: https://openrouter.ai/docs/models
> 
> <img alt="image" width="481" src="https://private-user-images.githubusercontent.com/11829944/366994634-f62ef268-e162-434b-ac0c-bd5600e59c2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjI2MDgsIm5iZiI6MTcyNjE2MjMwOCwicGF0aCI6Ii8xMTgyOTk0NC8zNjY5OTQ2MzQtZjYyZWYyNjgtZTE2Mi00MzRiLWFjMGMtYmQ1NjAwZTU5YzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5Mzc2ZWM2ZWU0OTk2MjBhNmQyNmEwZDVmMzQ2OGVjZWRmMTFmNWI2NGNkNDA2ZmU4MzljNTg2MTMxN2ZmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NNjFhxjxA6rG6MS1I_ZctrnjnkxmZV5JRW7iAkU6cPg"> <img alt="image" width="778" src="https://private-user-images.githubusercontent.com/11829944/366994820-5dea5cc5-e6ed-4189-bd68-8f68ad6c3b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjI2MDgsIm5iZiI6MTcyNjE2MjMwOCwicGF0aCI6Ii8xMTgyOTk0NC8zNjY5OTQ4MjAtNWRlYTVjYzUtZTZlZC00MTg5LWJkNjgtOGY2OGFkNmMzYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjlhOTBiYWUxODlhYjFkNTA1ZjZkM2M2Y2Y5MzgwM2Q0YTYzNGQwZjU4OTc5NmQwNGVhZGFmZTEwY2U3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hyEgdh8EMeaDx935qYpCG0j6sT_9A-vx-QjhxoLsuyM">

但是计算方式不知道怎么算的，很贵。

**Comment by chatterzhao** [comment] 2024-09-12 17:40
> use: https://openrouter.ai/docs/models
> 但是计算方式不知道怎么算的，很贵。
> 我创建了一个avalonia项目的hello world 就扣了$0.235，相当于扣了1-2M token

> <img alt="image" width="481" src="https://private-user-images.githubusercontent.com/11829944/366994634-f62ef268-e162-434b-ac0c-bd5600e59c2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjI2MDgsIm5iZiI6MTcyNjE2MjMwOCwicGF0aCI6Ii8xMTgyOTk0NC8zNjY5OTQ2MzQtZjYyZWYyNjgtZTE2Mi00MzRiLWFjMGMtYmQ1NjAwZTU5YzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5Mzc2ZWM2ZWU0OTk2MjBhNmQyNmEwZDVmMzQ2OGVjZWRmMTFmNWI2NGNkNDA2ZmU4MzljNTg2MTMxN2ZmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NNjFhxjxA6rG6MS1I_ZctrnjnkxmZV5JRW7iAkU6cPg"> <img alt="image" width="778" src="https://private-user-images.githubusercontent.com/11829944/366994820-5dea5cc5-e6ed-4189-bd68-8f68ad6c3b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjI2MDgsIm5iZiI6MTcyNjE2MjMwOCwicGF0aCI6Ii8xMTgyOTk0NC8zNjY5OTQ4MjAtNWRlYTVjYzUtZTZlZC00MTg5LWJkNjgtOGY2OGFkNmMzYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjlhOTBiYWUxODlhYjFkNTA1ZjZkM2M2Y2Y5MzgwM2Q0YTYzNGQwZjU4OTc5NmQwNGVhZGFmZTEwY2U3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hyEgdh8EMeaDx935qYpCG0j6sT_9A-vx-QjhxoLsuyM">

**Comment by saoudrizwan** [comment] 2024-09-16 11:41
Please see https://github.com/saoudrizwan/claude-dev/issues/230#issuecomment-2340575426

**Closed by saoudrizwan** 2024-09-16 11:41 UTC
