### ISSUE TITLE
Add rate limit information

### ISSUE THREAD

**Issue by CiberNin** [saoudrizwan/claude-dev#54] opened 2024-08-08 21:38 UTC
By my reading, the API should be returning how long until rate limit blocking wears off so you should be able to show a loading bar if you hit rate limit.

**Comment by drhouse** [comment] 2024-08-19 19:26
Is there a place that shows you rate limit timings? Is it on Anthropic's API website?

**Comment by saoudrizwan** [comment] 2024-09-02 17:20
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/186

**Closed by saoudrizwan** 2024-09-02 17:20 UTC
Labels: enhancement
