### ISSUE TITLE
OpenRouter as Groq Llama 3 

### ISSUE THREAD

**Issue by kiranmaya** [saoudrizwan/claude-dev#122] opened 2024-08-17 17:16 UTC
OpenAi and Groq Api and LM Studio API paths are similar, to get llama 3.1 model in this extension,
make the following changes, and use groq key as openai apikey.

file : openRouter.ts:
baseURL: "https://api.groq.com/openai/v1",

file :  api.ts:
export const openRouterDefaultModelId: OpenRouterModelId = "llama3-groq-70b-8192-tool-use-preview"

export const openRouterModels = {
"llama3-groq-70b-8192-tool-use-preview": {
		maxTokens: 8192,
		supportsImages: false,
		supportsPromptCache:false,
		inputPrice: 0.0, 
		outputPrice: 0.0, 
	},"mixtral-8x7b-32768": {
		maxTokens: 8192,
		supportsImages: false,
		supportsPromptCache:false,
		inputPrice: 0.0, 
		outputPrice: 0.0, 
	},

in setting panel,
custom instructions 

try this prompt 
`wrap your tools calls like this <tool_call>your content here</tool_call>
avoid <tool_response> <function_call> <function> for tool calling 
`
The tool calls are working fine, but the model is fragile compared to the anthropic/claude-3.5-sonnet , with an 8k maxtokens limit.

**Comment by saoudrizwan** [comment] 2024-09-02 16:31
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/30

**Closed by saoudrizwan** 2024-09-02 16:31 UTC
