### ISSUE TITLE
OpenAI Compatible API returning "404 status code (no body)" - 

### ISSUE THREAD

**Issue by Lveb2436** [saoudrizwan/claude-dev#375] opened 2024-09-24 01:08 UTC
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

QWEN 2.5 72B INSTRUCT

### What happened?

When Claude DEV tries to connect to the HYPERVOLIC provider’s API, the request response results in a 404 status code (no body)

![image](https://github.com/user-attachments/assets/3d860359-c2a5-402a-ac23-2eafe072bd79)

**** Configuration Parameters ****

![image](https://github.com/user-attachments/assets/be374728-bee3-444c-b452-8385d7c14b8b)

API Provider: Open AI Compatible
Base URL: https://api.hyperbolic.xyz/v1/chat/completions
API KEY: {USER KEY}
Model ID: Qwen/Qwen2.5-72B-Instruct.

**** Considerations ****

![image](https://github.com/user-attachments/assets/7e872d9d-0956-4fb3-85db-0bd79f2fa1bd)

-It is worth mentioning that the same model and provider work correctly in both Continu Dev Extension and Aider.
-There is a video on YouTube with the same configuration, and it works correctly.
-VS Code was reinstalled from scratch.
-The Claude Dev extension was reinstalled in different versions (same error occurs in the latest version).

"I tested all the available models from the HIPERVOLIC provider, and only the following models produce the previously described error:"

-Qwen/Qwen2.5-72B-Instruct
-deepseek-ai/DeepSeek-V2.5
-NousResearch/Hermes-3-Llama-3.1-70B
-meta-llama/Meta-Llama-3.1-405B
-meta-llama/Meta-Llama-3.1-405B-FP8

***** Console LOG *****.

![image](https://github.com/user-attachments/assets/f0be4a7e-75cc-4b94-91bc-7474cffa6b10)

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment] 2024-09-24 01:11
Thank you for sharing, closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/340 but can you pls add details there if there's something new that isn't already mentioned in that issue

**Closed by saoudrizwan** 2024-09-24 01:11 UTC
Labels: bug

**Comment by allentofight** [comment] 2024-09-24 10:36
how to show the custom base url again, I set it to one,but I find the key is error, want to change it ,but I cannot find how to show the custom base url
