### ISSUE TITLE
The diagnostics monitoring update isn't working as expected

### ISSUE THREAD

**Issue by zytakeshi** [saoudrizwan/claude-dev#313] opened 2024-09-16 03:48 UTC
After 1.7.0 it became unusable because it keeps sending VSCODE errors which are often invalid and unrelated, especially when editing files that are not meant to be running on windows. 

Please at least give us an option to choose whether to send erros of vscode or not.

**Comment by saoudrizwan** [comment] 2024-09-16 11:03
I just released v1.7.3 that now only uses workspace errors (and not warnings since this may be too distracting in large projects). I've also added the following instructions to the system prompt:
- You will automatically receive workspace error diagnostics in environment_details. Be mindful that this may include issues beyond the scope of your task or the user's request. Focus on addressing errors and warnings relevant to your work, and avoid fixing pre-existing or unrelated issues unless the user specifically instructs you to do so.
- If you are unable to resolve errors provided in environment_details after a few attempts, consider using ask_followup_question to ask the user for additional information, such as the latest documentation related to a problematic framework, to help you make progress on the task.

Please give the new update a go and let me know how it works for you.

Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/315

**Closed by saoudrizwan** 2024-09-16 11:03 UTC

**Comment by zytakeshi** [comment] 2024-09-16 14:42
Adding such prompt helps but I still think an option to toggle this feature on and off is a must.
