### ISSUE TITLE
Claude tried to use write_to_file 

### ISSUE THREAD

**Issue by lars67** [saoudrizwan/claude-dev#172] opened 2024-08-26 09:37 UTC
"Claude tried to use write_to_file " I get this tons of times the last few days. Running 1.4.11
Irrelevant of model choice. Any ideas?

![image](https://github.com/user-attachments/assets/91924f86-fbee-4a43-a0b8-97c369f295bc)

**Comment by aaronbferrell** [comment] 2024-08-26 17:56
Having the same issue... I keep having to try and close and a re-open a prompt,. Not sure if there's any other easier way to fix this?

**Comment by saoudrizwan** [comment] 2024-09-02 17:11
This tends to happen for really large files, can you pls try breaking your file into smaller files (or even asking claude dev to do this). Also it may help to tell claude to lazy code and then revert the `//rest of code here` comments with the new revert block update https://x.com/sdrzn/status/1829873616441278915

Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/127

**Closed by saoudrizwan** 2024-09-02 17:11 UTC
