### ISSUE TITLE
Add Support for Custom Prompts Folder and Selector in UI

### ISSUE THREAD

**Issue by LFSousa** [saoudrizwan/claude-dev#35] opened 2024-07-30 17:00 UTC
Hi,

I'd love to see a feature that lets users create a folder for custom prompts in the current working directory. These prompts should be in Markdown format (.md) and selectable via a dropdown in the UI.

**Key Features:**
- **Custom Prompts Folder:** Let users store prompts in a specific directory.
- **UI Selector:** Add a dropdown to switch between these prompts.
- **Variable Support:** Allow using variables like `{{TASK}}` in the prompts. For each `{{VAR}}`, create an input field in the UI.

**Use Case:**
This would make it super easy to switch between different prompts for various tasks or projects. For instance, someone working on multiple projects can have specific prompts for each and switch between them easily. The variable support would allow users to dynamically adjust prompt content based on their needs.

**Example:**
- **Folder Structure:**
  ```
  ./prompts
  ├── readme_prompt.md
  ├── doc_prompt.md
  └── general_prompt.md
  ```

- **Prompt File Content:**
  ```markdown
  Before proceeding with the request, read the following documents:
  - [README.md](./README.md)
  - [Documentation](./docs)
  
  Task: {{TASK}}
  ```

- **UI Implementation:**
  When selecting a prompt with `{{TASK}}`, an input field labeled "TASK" appears in the UI to enter the specific task dynamically.

**Benefits:**
- **Customization:** Create tailored prompts for different tasks.
- **Efficiency:** Switch between prompts quickly without manual changes.
- **Flexibility:** Use variables like `{{TASK}}` to dynamically change prompt content.

Thanks for considering this feature!

**Comment by CiberNin** [comment] 2024-07-30 17:47
feels like stuff relevant to the extension configuration/data should be stored under .vscode

**Comment by saoudrizwan** [comment] 2024-09-23 22:40
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/136

**Closed by saoudrizwan** 2024-09-23 22:40 UTC
Labels: enhancement
