### ISSUE TITLE
Failed when calling deepseeker coder model from openrouter API

### ISSUE THREAD

**Issue by dynax4u** [saoudrizwan/claude-dev#163] opened 2024-08-24 04:40 UTC
![screen](https://github.com/user-attachments/assets/432d4d17-2679-4bc8-956e-befd321311b1)
Please modify the corresponding endpoint to allow Claude Dev calling the latest deepseek coder v2 model, this model works well and is cheap.Thanks.

**Comment by saoudrizwan** [comment] 2024-08-24 21:37
Claude dev doesn't work well with most models, but there are some forks you could try if you'd like to experiment with them. Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/30

**Closed by saoudrizwan** 2024-08-24 21:37 UTC
