### ISSUE TITLE
Feature request: auto complete unchanged code

### ISSUE THREAD

**Issue by zyzhang1130** [saoudrizwan/claude-dev#314] opened 2024-09-16 07:19 UTC
When the script has more than 1000 lines, Claude 3.5 sonnet tends to output
`// ... (rest of the file unchanged)` for the unchanged part. It is understandable because there are just too many unchanged lines to regurgitate. In this case, it would be very helpful if we could implement an auto-complete function to fill in the missing lines that are replaced with `// ... (rest of the file unchanged)` by Claude 3.5 sonnet.

**Comment by shameed123** [comment] 2024-09-16 20:18
So needed.  It is such a fundamental part of a coding assistant.

**Comment by shameed123** [comment] 2024-09-16 20:23
The thing is that it actually saves tokens for not including the code in the response.  It would be nice if it could be substituted on the cient (editor) side.  But I understand it is a lot easier if we can force Claude to send the full file back instead.  It already eats through the credits as is though.  :-D

**Comment by asdf8675309** [comment] 2024-09-16 20:55
My expenses this month are 75% cache read/writes and 25% output tokens.  thats on 108M in and 1.3M out - FWIW.  So yes if it did output the existing blocks it out possibly eat some more tokens.  I view it though as time costs money - so I'm ok with paying for the output tokens if it outputs the correct stuff.

**Comment by quinn** [comment] 2024-09-17 16:54
duplicate of https://github.com/saoudrizwan/claude-dev/issues/289

**Comment by zyzhang1130** [comment] 2024-09-17 17:00
> duplicate of #289

Not exactly duplicate, as I think a warning is not sufficient to solve this issue; nor is a good system message. I think it is pretty common for a script to have over a thousand lines nowadays, so expecting Claude to output the entire script in this case is simply unrealistic.

**Comment by zyzhang1130** [comment] 2024-09-17 17:01
> I've seen this many times as well (I think we all have) - I've added a few things to my claude-dev prompt asking that it not do that. I also have a .claude-dev file in my project directory where I explain what the project is, the limitations, the requirements, how it is structured. Then I spell out some Core Rules in brackets. I give directions in there like these, but it still happens - but it seems like it's less than before.
> 
> My "custom instructions prompt" includes what we are working on as well as some guidelines including like this:
> 
> You are a [Library/Function/Toolkit/Language] Expert programmer tasked with creating well-commented, accurate, and maintainable code that compiles every time. Your goal is to review, modify, and improve existing code while adhering to specific guidelines and best practices. Follow these instructions carefully:
> 
> 1. Read the current file content you have been given
> 2. After reviewing the file content, suggest changes and improvements while following these guidelines:
>    a. Fix all nullable reference type errors.
>    b. Include error traps and logging for all buttons and data entry fields.
>    c. Minimize changes to the existing code when adding new functionality.
>    d. Format dates consistently (MM/DD/YYYY) and currency values with two decimal places.
>    e. Do not remove functions and classes that are currently in use.
> 3. If you encounter any warnings while building the project, address and fix them before moving on to other tasks.
> 4. Provide your suggested changes and improvements inside <code_changes> tags. Include comments explaining the rationale behind significant modifications.
> 5. If you have any additional recommendations or best practices that should be implemented, include them in a separate  section.
> 6. Remember the project description and core rules  can be found in the .claude-dev file.
>    Remember to maintain a professional and expert tone throughout your response. Focus on creating efficient, scalable, and maintainable code that adheres to development best practices
> 
> .claude-dev Responding with -- Previous functions remain unchanged ... is NOT ALLOWED - You will be penalized for each response that is this or similar. When using write_to_file, it is critical to include the entire file content in the response. Do not use partial updates or placeholders. Omitting any part of the file can lead to incomplete or malfunctioning code, which can have serious consequences for the user's project. Instead of // ... [Keep existing code] You MUST keep the existing code in place. leaving out the existing code breaks the program. Your goal is to help the user, not cause them more work. Instead of // Order-specific functions (Order could be something else) keep the specific function. You are not allowed to delete blocks of code and replace it with a comment. Instead of // ... [Keep existing generic functions] -- leave the existing Generic Functions in place. Complete tasks fully. Do not use comments like //unchanged in the actual code, include the actual unchanged code instead

When a script is too large, no good system prompt can effectively address this issue unfortunately.

**Comment by HarryBak** [comment] 2024-09-18 18:17
I believe it's just a standard diff so you can revert on the UI and claude sends back "user edit" with the part you reverted.

**Comment by quinn** [comment] 2024-09-18 18:21
@zyzhang1130 I agree a warning is not sufficient. 

I think these issues can be solved by instructing claude to output a patch, rather than what is currently happening, which I assume is claude outputs the whole file and then the vscode plugin creates the diff by comparing Claude's output to the current version of the file. This should solve this issue, as well as the other issues i mentioned

**Comment by quinn** [comment] 2024-09-18 18:29
@saoudrizwan I wonder if it would make sense to add a new command, separate from `write_to_file` called `apply_patch`? and claude is instructed to use this command in cases where it would add those comments?

**Comment by saoudrizwan** [comment] 2024-09-23 21:35
@quinn I've played around with patch diffs/structured output, but this significantly reduces claude's quality of responses. As in he's unable to make a simple snake game on his first try anymore. This is probably bc it's trained on way more whole code files rather than diffs. This should be a problem of the past when anthropic releases their new fast edit mode feature soon, but for now I've created a wiki doc that should help work around this problem: https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments

**Closed by saoudrizwan** 2024-09-23 21:35 UTC

**Comment by shameed123** [comment] 2024-09-23 23:16
Hi @saoudrizwan, thanks for looking into it  This is what I have been doing - using the diff and manually merge the code.  But this takes the fun out of it.  There two problems: Not everytime you can merge the code by clicking the arrow because it would overwrite the new code as well, and then due to some bug sometimes clicking the arrow does not work at all.  Not sure if it is VS code issue or it is Claude Dev issue.

The question is, why can't Claude Dev merge for us.  It does not have to get the diff from Claude model, it can create its own diff and merge itself.
