### ISSUE TITLE
add openai model

### ISSUE THREAD

**Issue by benjamix95** [saoudrizwan/claude-dev#204] opened 2024-08-31 14:33 UTC
hi, can you add openai model standalone, not with openrouters, the latest model it's very huge update chatgpt-4o-latest, it's so far improoved

**Comment by saoudrizwan** [comment] 2024-09-01 03:19
I actually tried to add openai support yesterday but my credit card kept getting declined on their dashboard so I couldn't test it, but as soon as I get that worked out I'll add this

**Comment by benjamix95** [comment] 2024-09-01 11:19
thank you so much for your efforts. your estension is the best.

**Comment by AnsonLai** [comment] 2024-09-01 19:02
Similarly, I was thinking of building in Gemini support.  tl;dr the long context might be very helpful

**Comment by saoudrizwan** [comment] 2024-09-02 17:24
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/159

**Closed by saoudrizwan** 2024-09-02 17:24 UTC

**Comment by saoudrizwan** [comment] 2024-09-04 01:52
v1.5.19 now supports OpenAI compatible endpoints!

**Comment by oracleofsin** [comment] 2025-05-30 14:05
when is it possible to run this without paying someone we run our own llms at work that are openapi compatible endpoints there is zero chance im paying cline creators to use this the way it sucks up credits lol nice try though
